### ISSUE TITLE
ImportError: cannot import name 'NavigationDrawer'

### ISSUE THREAD

**Issue by samaranin** [HeaTTheatR/CreatorKivyProject#1]
Trying to run empty project and getting this error.
Maybe, because of this commit: 
'NavigationDrawer: New NavigationDrawer using kivy.garden.navigationdrawer' https://gitlab.com/kivymd/KivyMD/commit/7e99cef589007931d0fd02d3a29cfd745510c178
Any chances to fix that?

**Comment by Guest007** [comment]
Too huge changes in KivyMD. 
@HeaTTheatR are you plan to update this project? It's very interesting, but not so fresh :-)

**Comment by shuron43** [comment]
Look at the fork https://github.com/shuron43/CreatorKivyProject.git

**Comment by HeaTTheatR** [comment]
The project will be updated soon.
