### ISSUE TITLE
Не могу создать проект

### ISSUE THREAD

**Issue by lapitskiy** [HeaTTheatR/CreatorKivyProject#11]
Подскажите, тупой вопрос
создал в терминале проект python main.py focus 1.0.1 Slovoninza E:\Work\python\focus
но при запуске (run) main.py в pycharm, выдает такую ошибку 

[INFO   ] Logger: Record log in C:\Users\Egor\.kivy\logs\kivy_19-12-07_8.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Users\Egor\untitled\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Users\Egor\untitled\Scripts\python.exe"
[INFO   ] Logger: Purge log fired. Analysing...
[INFO   ] Logger: Purge finished!
[INFO   ] Creator Kivy Project version: 2.3.0
[WARNING] 
Use a script with string arguments:

'name' - project name
'version' - project version
'path' - project directory
'repo' - address of the repository on GitHub (optional)
'author' - name of the author of the project (optional)
'mail' - mail of the author of the project (optional)
'site' - project site (optional)

**Comment by HeaTTheatR** [comment]
И что не понятно?
