### ISSUE TITLE
Need documentation building applications with pyinstaller.

### ISSUE THREAD

**Issue by aprilahijriyan** [HeaTTheatR/CreatorKivyProject#13]
how do I package a kivy GUI with pyinstaller or buildozer?

**Comment by HeaTTheatR** [comment]
https://github.com/HeaTTheatR/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec
https://github.com/HeaTTheatR/KivyMD/blob/master/demos/kitchen_sink/pyinstaller.spec
